version: '3'
services:
  keycloak:
    container_name: "${SHANOIR_PREFIX}keycloak"
    environment:
      - SHANOIR_ADMIN_EMAIL
      - SHANOIR_ADMIN_NAME
      - SHANOIR_URL_HOST
      - SHANOIR_URL_SCHEME
      - SHANOIR_SMTP_HOST
      - SHANOIR_MIGRATION
      - SHANOIR_KEYCLOAK_USER
      - SHANOIR_KEYCLOAK_PASSWORD
      - SHANOIR_ALLOWED_ADMIN_IPS
      - SHANOIR_DB_ADDR
      - SHANOIR_KEYCLOAK_DB_PORT
    restart: always
    build: ./docker-compose/keycloak
    networks:
      - shanoir_ng_network
    ports:
      - "8080:8080"

volumes:
  certificate-share-data:
  logs:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  shanoir_ng_network:
